spring.application.name=url-shortener-sb
spring.datasource.url=jdbc:mysql://localhost:3306/url-shortenerdb
spring.datasource.username=root
spring.datasource.password=gaurav@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=ce9be2ff8fafe3a8a42d962ff496ae6d01846ae0acc69f90515bfaa37764ae96
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.url.shortener=DEBUG